export default function logRegForm() {
    // const divStatus = document.createElement("div");
    // divStatus.className = "login__status";
    // divStatus.id = "status";
    // section.append(divStatus);
    // const paramStatus = document.createElement("p");
    // paramStatus.className = "login__status_txt";
    // paramStatus.id = "status_txt";
    // paramStatus.innerHTML = "Enter email and password";
    // divStatus.append(paramStatus);
    // const divForm = document.createElement("div");
    // divForm.className = "login__form";
    // section.append(divForm);
    // const divFormContentEmail = document.createElement("div");
    // divFormContent.className = "login__form_content";
    // divForm.append(divFormContentEmail);
    // const parFormMail = document.createElement("p");
    // parFormMail.className = "login__form_txt";
    // parFormMail.innerHTML = "Email";
    // const inputEmail = document.createElement("input");
    // inputEmail.className = "login__form__inpt";
    // inputEmail.id = "email";
    // inputEmail.type = "email";
    // divFormContentEmail.append(parFormMail, inputEmail);
    // const divFormContentPassword = document.createElement("div");
    // divFormContentPassword.className = "login__form_content";
    // divForm.append(divFormContentPassword);
    // const parFormPassword = document.createElement("p");
    // parFormPassword.className = "login__form_txt";
    // parFormPassword.innerHTML = "Password";
    // const inputPassword = document.createElement("input");
    // inputPassword.className = "login__form__inpt";
    // inputPassword.id = "password";
    // inputPassword.type = "password";
    // divFormContentPassword.append(parFormPassword, inputPassword);
    // const buttonLogin = document.createElement("button");
    // buttonLogin.className = "login__form_btn";
    // buttonLogin.id = "btn-login";
    // buttonLogin.type = "submit";
    // buttonLogin.innerHTML = "Log In";
    // divForm.append(buttonLogin);
    // const buttonPassword = document.createElement("button");
    // buttonPassword.className = "login__form_btn signUp";
    // buttonPassword.id = "btn-sign-up";
    // buttonPassword.type = "submit";
    // buttonPassword.innerHTML = "Sign Up";
    // divForm.append(buttonPassword);
}
